### ISSUE TITLE
This is so cool!

### ISSUE THREAD

**Issue by green3g** [j-muller/python-tplink-smarthome#1]
Just wanted to leave a friendly note and tell you how neat this is! Thanks for publishing!

**Comment by green3g** [comment]
Just curious if you could publish the updated version to pipi? It looks like you've fixed some issues I'm running into:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Projects/cat-water-pump/env/lib/python3.7/site-packages/gpiozero/mixins.py", line 557, in fill
    self.parent._fire_events(self.parent.pin_factory.ticks(), self.parent.is_active)
  File "/home/pi/Projects/cat-water-pump/env/lib/python3.7/site-packages/gpiozero/mixins.py", line 368, in _fire_events
    self._fire_activated()
  File "/home/pi/Projects/cat-water-pump/env/lib/python3.7/site-packages/gpiozero/mixins.py", line 344, in _fire_activated
    self.when_activated()
  File "main.py", line 25, in activate
    self.device.turn_on()
  File "/home/pi/Projects/cat-water-pump/env/lib/python3.7/site-packages/tplink_smarthome/plug.py", line 12, in turn_on
    return self.recv()
  File "/home/pi/Projects/cat-water-pump/env/lib/python3.7/site-packages/tplink_smarthome/device.py", line 89, in recv
    length, *_ = struct.unpack('>I', chunk[0:4])
struct.error: unpack requires a buffer of 4 bytes
```
